language: ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6

os:
  - osx
  - linux

matrix:
  # http://rubies.travis-ci.org/
  exclude:
  - os: osx
    rvm: 1.9
  - os: osx
    rvm: 2.0
  - os: osx
    rvm: 2.1
  - os: osx
    rvm: 2.2
